// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Community_Basic","status":true,"description":"Basic plugin for manipulating important parameters.","parameters":{"cacheLimit":"20","screenWidth":"816","screenHeight":"624","changeWindowWidthTo":"","changeWindowHeightTo":"","renderingMode":"auto","alwaysDash":"off"}},
{"name":"MadeWithMv","status":false,"description":"Show a Splash Screen \"Made with MV\" and/or a Custom Splash Screen before going to main screen.","parameters":{"Show Made With MV":"true","Made with MV Image":"MadeWithMv","Show Custom Splash":"false","Custom Image":"","Fade Out Time":"120","Fade In Time":"120","Wait Time":"160"}},
{"name":"YEP_EventChasePlayer","status":true,"description":"v1.02 When a player is in the proximity of a certain event,\r\nthe event will start chasing or fleeing from the player.","parameters":{"Sight Lock":"300","See Player":"true","Alert Timer":"120","Alert Balloon":"1","Alert Sound":"Attack1","Alert Common Event":"0","Return After":"true","Return Wait":"180"}},
{"name":"upp_minimapPro","status":false,"description":"Version: 2.3.2 | A minimap for your games.","parameters":{"---Location---":"","Minimap X":"12","Minimap Y":"52","Name Display X":"12","Name Display Y":"12","---Color---":"","Impassable Color":"28, 107, 124, 1","Passable Color":"86, 188, 192, 1","Outline Color":"0, 0, 0, 0.25","Player Color":"255, 255, 0, 1","Map Name BGColor":"rgba(0, 0, 0, 0.5)","---Scaling---":"","Default Scale":"2","---Config Settings---":"","Config BG Location":"title1","Config BG":"WorldMap"}},
{"name":"KMS_Minimap","status":false,"description":"[v0.2.0] Display minimap.","parameters":{"Map rect":"600, 47, 200, 140","Grid size":"10","Blink time":"180","Foreground color":"rgba(255,255,255,0.7)","Background color":"rgba(255,10,0,0.2)","Mask style":"2","Mask radius":"48"}}
];
